### ISSUE TITLE
Add a Dashboard widget

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#108]
The following should be displayed in the dashboard widget

- Total number of emails
- Link to view the logs

Requested at https://wordpress.org/support/topic/great-could-be-even-better-2/

**Comment by mariadanieldeepak** [comment]
@sudar,

I've implemented the Dashboard widget and verified the count value when available lists correctly and also when the table is empty, the count value is listed as 0.

![image](https://user-images.githubusercontent.com/17510033/31304894-79d71682-ab4a-11e7-94a6-e10a95ac9967.png)

![image](https://user-images.githubusercontent.com/17510033/31304895-8015bfe4-ab4a-11e7-92b6-b8232cc59072.png)

**Comment by mariadanieldeepak** [comment]
**Suggestion:** Improve the widget by adding footer links to Settings, Logs & Addons.

![image](https://user-images.githubusercontent.com/17510033/31324845-7ddea782-acd4-11e7-86b6-16f70d2534ea.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

Go for it and send me a PR

**Comment by mariadanieldeepak** [comment]
👍

**Comment by mariadanieldeepak** [comment]
@sudar,

The changes have been implemented.

**Before**

![image](https://user-images.githubusercontent.com/17510033/31325583-36b4c726-acdc-11e7-887d-f8c580fdbd8e.png)

**After**

![image](https://user-images.githubusercontent.com/17510033/31325585-3aa7c496-acdc-11e7-86c1-02d4a45f463e.png)

**Comment by mariadanieldeepak** [comment]
I was thinking to come up with something as shown here

![image](https://user-images.githubusercontent.com/17510033/31325605-837b7d0c-acdc-11e7-824d-1d18addfaa7c.png)

When we have some more metrics, I'll implement something more widgety like the above screenshot.

**Comment by sudar** [comment]
@mariadanieldeepak 

Thanks a good suggestion.

For Bulk WP we have lot of data. So we should be able to showcase that.
