### ISSUE TITLE
Build a Plugin to send emails in scheduled intervals

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#120]
The Plugin should send emails HTML and text emails with all evil content (Quotes, scripts, anything that could potentially damage the system).

**Comment by mariadanieldeepak** [comment]
This could be a feature within Email Log plugin itself. When it is within the plugin, there should be an option to send Loreum Ipsum text and HTML emails as well.

That way Users can quickly send out an Email and find the if the plugin logs it.

**Comment by sudar** [comment]
@esudalaimadan 

No need to work on this.

I am closing this, since I feel that we don't need it anymore.
