### ISSUE TITLE
Suggestion: Warn Users about potential non-logging circumstances 

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#121]
It could be a nice addition to notify Users (via Admin notices) when a potential plugin, that routes emails, via 3rd party SMTP/HTTP servers other than `wp_mail()` method is found.

May be start with a small list of plugins like Mail Poet, Mail Chimp, etc., and build an exhaustive list over time. This will avoid Users complaining on the forum that the emails aren't logged.

**Comment by sudar** [comment]
Good suggestion. Let's start building the list first.

**Comment by sudar** [comment]
@mariadanieldeepak 

Document the list of scenarios when email may not be captured by the plugin.

For now only document the list. We will implement it once we have the list.

**Comment by mariadanieldeepak** [comment]
- Identify the list of Plugins that are not logging.
- Try sending PR by adding filters that sends WP Mail information
- If not, show a notice on the admin screen saying Email won't be logged

**Comment by mariadanieldeepak** [comment]
Since there were not many non-logging scenarios, we're closing this issue. We might re-open later as needed.
