### ISSUE TITLE
Star an Email log

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#122]
Ability to star an email log. The starred email logs can be filtered seperately.

- [x] Create a new user meta to store the list of log ids that were stared.
- [x] Provide an interface in the View Log page where the user can star an email log. Clicking again will unstar the email.
- [x] Use AJAX to store the star/unstar of an email log
- [x] Once an email log is stared it will be stored in user meta
- [x] Provide filters to show only started email logs

Originally this issue was tracking both Star an Email and Save a search feature. I have created #225 to track Save a Search feature.

Here is the original description.

**Original Description**

Right now the Email Log page lists all emails that are logged and currently doesn't have a feature to star an email.

Use case: Let us say, I want to refer to an email that I found via search (from the Logs page) without repeating the search. In a membership site, this could be a good use case, to see if an email is sent from a particular email.

In this case we could do things, 

- Introduce a saved search feature (like Evernote does)
- Introduce a favourite button (like Gmail does, WordPress plugins repo does)

Let me know which one would you prefer or you think would be suitable :)

**Comment by sudar** [comment]
Both are good suggestions.

I would prioritise star/favourite option before saved search.

**Comment by sudar** [comment]
@esudalaimadan 

Daniel has already implemented most of it and also has a PR. But he mentioned that he was facing some issues.

Have a look at the PR and first identify the issues and the document them here. After that work on fixing them.

**Comment by esudalaimadan** [comment]
I am not able to star or unstar a log. Following JS error in the console.
`ReferenceError: elEmailLog is not defined`

**Comment by sudar** [comment]
@esudalaimadan 

I have fixed the JavaScript error. Check now.

**Comment by sudar** [comment]
@esudalaimadan 

There were some code review issues in the branch and I have fixed all of them.

Can you test the branch once to make sure everything works?

**Comment by sudar** [comment]
Fixed by #244
