### ISSUE TITLE
Suggestion: Notify admin when Email Logs meet a threshold

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#124]
Problem: Right now, there is no way for the User to figure out if the DB is growing until he checks the View Logs page. This will let the DB grow invariably if the site sends out hundreds of emails in a day.

Solution: Let's add a threshold notifier in Settings page, and notify the Admin via the provided email so he can go ahead and delete the logs. This is also a good opportunity to up sell the Auto Delete Logs plugin.

The following needs to be done for this task.

- [x] Add a new section in the settings screen called "Database Size notification"
- [x] Add a new checkbox called "Notify if there are more than x logs". x should be a textbox. Also display a message below this that say "There are x email logs currently logged in the database"
- [x] Add a new textbox called email, which by default has the admin email address.
- [x] Every time when a new email is logged check if there is already a cron job scheduled. If not schedule a cron job to run after 30 minutes.
- [x] In the cron job check if total number of email logs has exceeded the threshold that is specified.
- [x] If yes, then send an email and also store a new setting variable called 'log_threshold_met'. No more emails should be sent after that.
- [x] A new message should now appear on top of email log list screen, with the following message. This message should be dismissible.

> Currently there are x email logs logged, which is more than the threshold that is set in the settings screen (link to settings screen). You can delete some logs or increase the threshold. You can also use our Auto Delete Logs add-on to automatically delete logs (link to the add-on)."

---

## Attached PR(s)
https://github.com/sudar/email-log/pull/152

**Comment by mariadanieldeepak** [comment]
Progress made so far:

![image](https://user-images.githubusercontent.com/17510033/43823210-02f443ca-9b0c-11e8-8a69-d5f2fae94681.png)

![image](https://user-images.githubusercontent.com/17510033/43823214-06074e54-9b0c-11e8-8dc3-809875f4dc33.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

> Every time when a new email is logged check if there is already a cron job scheduled. If not schedule a cron job to run after 30 minutes.

Currently we don't have an action, to indicate that email is logged either in https://github.com/sudar/email-log/blob/dev/2.3.0/include/Core/EmailLogger.php#L73 or in https://github.com/sudar/email-log/blob/dev/2.3.0/include/Core/DB/TableManager.php#L98-L103

Should we add the filter in `include/Core/EmailLogger.php`? I ask this because it makes sense to add it in Table Manager, if we're saving the Email in more than one place. But I couldn't think of a scenario where we would end up saving emails in more than one place.

**Comment by sudar** [comment]
@mariadanieldeepak 

Add an **action** called `el_email_log_inserted` just after the call to `insert_log` and pass the `$data` as param to it.

**Comment by mariadanieldeepak** [comment]
Progress:

Implemented the Cron and the email sending functionality.

![image](https://user-images.githubusercontent.com/17510033/43904149-a402ff2c-9c0b-11e8-9fd5-81424985f9b7.png)

The functionality respective to DB can be observed in the following screenshot.

![image](https://user-images.githubusercontent.com/17510033/43904338-00a9279c-9c0c-11e8-9977-70e8cb94a354.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

The development is now complete.

![image](https://user-images.githubusercontent.com/17510033/43971019-278f16fa-9ced-11e8-84f2-f68879e5658e.png)

And here is the respective PR https://github.com/sudar/email-log/pull/152

Though I'm happy with the result, yet I'm not happy with the code organization. I think we should move the `admin_notices` to a better suited place. Kindly review the code.

**Comment by mariadanieldeepak** [comment]
@sudar,

I've added couple of improvements along with fixing the review comments. Testing is remaining and I shall update you once it is complete.
