### ISSUE TITLE
Improve preview

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#125]
Right now the body tag and external css are getting stripped when preview the html email. This needs to be improved.

Requested at https://wordpress.org/support/topic/html-not-previewing-as-it-is/#post-9720018

---

## Attached PR(s)
https://github.com/sudar/email-log/pull/156

**Comment by mariadanieldeepak** [comment]
@sudar,

I won't be able to get this one in this sprint.

```
Originally planned for Aug 14th sprint
```

**Comment by mariadanieldeepak** [comment]
@sudar,

The development is completed. This is now ready for your review. The [PR](https://github.com/sudar/email-log/pull/156) is here.

**Before**

![image](https://user-images.githubusercontent.com/17510033/44853680-33d41e00-ac84-11e8-92e7-1177cb73090d.png)

![image](https://user-images.githubusercontent.com/17510033/44853623-0f784180-ac84-11e8-9547-85c2a17bfd52.png)

**After**

![image](https://user-images.githubusercontent.com/17510033/44853767-6b42ca80-ac84-11e8-8975-06abc0d82e58.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

Left some review comments.

While you are at it, also change the HTML tab as the default one.

**Comment by mariadanieldeepak** [comment]
@sudar,

 > Left some review comments.

Fixed the review comments.
