### ISSUE TITLE
Suggestion [Add-on]: Forwarded Emails Count in Dashboard

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#128]
After installing the Forward Email add-on, the User cannot see the count of Emails forwarded. This makes them suspect if the emails are ever forwarded.

Showing the forwarded email count in the Dashboard Widget, will make the product more meaningful. Also, in the Logs page, there can be a small Icon added if the respective Email is forwarded. This will also enhance the impact.

**Comment by sudar** [comment]
Good suggestion. Let's move it to add-on repo and prioritise it.

**Comment by sudar** [comment]
@mariadanieldeepak 

For this sprint, just move this to the add-on repo and close the issue here.

**Comment by mariadanieldeepak** [comment]
Closing this issue since we're not already capturing the data. Might revisit in case needed in the future.
