### ISSUE TITLE
Hide the Pro add-on upsell once a license key has been entered

### ISSUE THREAD

**Issue by johnbillion** [sudar/email-log#131]
The upsell message for the additional fields add-on is still shown, despite my having entered a valid license key on the Email Log -> Add-ons screen.

I think it should be hidden once a license key has been entered, even if the additional fields add-on hasn't specifically been activated.

**Comment by sudar** [comment]
It's currently hidden once the 'Additional fields' add-on is activated. But I agree with you that it doesn't make sense to have it once a bundle license is activated.

Will have it implemented for next release.
