### ISSUE TITLE
Suggestion: Provide option to choose a default view

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#138]
By default, Raw HTML is selected.

---

## Attached PR(s)
https://github.com/sudar/email-log/pull/159

**Comment by sudar** [comment]
@mariadanieldeepak 

You mean while viewing the email content?

**Comment by mariadanieldeepak** [comment]
@sudar,

> You mean while viewing the email content?

Yeap

**Comment by sudar** [comment]
@mariadanieldeepak 

Let's change the default to HTML view.

No need to add this as a setting for now.
