### ISSUE TITLE
URL keeps appending leading to HTTP 414 “Request URI too long” error?

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#139]
When deleting Email Logs, the URL keeps appending the HTTP Referrer each time, leading to HTTP 414 error.

https://example.com/wp-admin/admin.php?page=email-log

A good to start to solution would be: https://stackoverflow.com/questions/2891574/how-do-i-resolve-a-http-414-request-uri-too-long-error

**Comment by sudar** [comment]
@mariadanieldeepak 

This should be fixed in https://github.com/sudar/email-log/commit/4f6c5bf06957442c6e0a5d39c2a6cd87b25b6dce

Can you try out the latest code from `dev/2.3.0` and see whether it fixes this issue?

**Comment by mariadanieldeepak** [comment]
@sudar,

The code in branch `dev/2.3.0` has fixed the issue. I don't see the URL being appended to HTTP Referrer each time I delete.

![image](https://user-images.githubusercontent.com/17510033/38165550-e79fe96a-3532-11e8-9913-f57c6b922f70.png)

![image](https://user-images.githubusercontent.com/17510033/38165556-034e95e4-3533-11e8-973c-ceda8b0a3eb5.png)
