### ISSUE TITLE
More Fields plugin throws exception

### ISSUE THREAD

**Issue by dnblankedelman** [sudar/email-log#14]
Hi Sudar-

Not sure if you want bugs for the commercial addons reported here or some other repo, but when I attempted to activate the more fields addon (with 1.5.4 installed), I get the following fatal error and the addon plugin refuses to activate:

````
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home2/honk/public_html/wp-content/plugins/email-log-more-fields/email-log-more-fields.php on line 53
````
That's the strangest error I've encountered in a while. My best shot at looking this error up suggests the problem is with the double colon on the line (::) even though that line looks fine to me. I wonder if something earlier in the code is triggering the error.

This is running on a 3.6.1 install with PHP version 5.2.17. Please let me know if you need any other info to debug this.

**Comment by sudar** [comment]
This is fixed in the addon.
