### ISSUE TITLE
Open all external links in a new tab

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#140]
- [ ] Add 'target="_blank"' to all links that open external urls.

**Comment by mariadanieldeepak** [comment]
@sudar,

This issue is prone to security vulnerability. We should be using Google's recommendations to fix the vulnerability.

https://developers.google.com/web/tools/lighthouse/audits/noopener

**Comment by mariadanieldeepak** [comment]
@sudar, Since it is Email Log's own website, we can be sure that no malicious code is being run. However, I found the vulnerability during my https://github.com/sudar/email-log/issues/182 testing.
