### ISSUE TITLE
HTML comments are getting rendered while previewing

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#146]
Reported at https://wordpress.org/support/topic/html-preview-displays-html-comments/

**Comment by mariadanieldeepak** [comment]
@sudar,

The HTML comments are not shown in the `Preview content as HTML` tab.

![image](https://user-images.githubusercontent.com/17510033/43727816-af4706d2-99c0-11e8-9675-b1284ef258b1.png)
 
![image](https://user-images.githubusercontent.com/17510033/43727881-e0534c0e-99c0-11e8-8a30-1269dd409e00.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

I have asked in WordPress forums for a screenshot. Let's put this on hold till then.

**Comment by sudar** [comment]
Closing this, since we can't replicate it and the original person who reported it has not responded.

We can open it again if we are able to replicate this issue.
