### ISSUE TITLE
Suggestion: Setting to limit Email Log entries

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#147]
@sudar,

The idea of having a setting to limit the log entries sounds great to me. Simple Login Log has a similar setting. Rather than days, we can limit it to a desired number.

![image](https://user-images.githubusercontent.com/17510033/42410162-d8e6b01c-8202-11e8-9fe5-99215061bc69.png)

Also, the functionality of [Auto Delete Logs](https://wpemaillog.com/addons/auto-delete-logs/) wouldn't contradict with this setting.

Kindly let me know your thoughts.

**Comment by sudar** [comment]
@mariadanieldeepak 

This looks like a duplicate of #124. What do you feel?

**Comment by mariadanieldeepak** [comment]
@sudar Yeap it is. Hence closing this.
