### ISSUE TITLE
Unable to run phpcs

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#154]
![image](https://user-images.githubusercontent.com/17510033/44096708-8e55f084-9ff9-11e8-8d5f-928f06992e69.png)

Identified as part of #105

**Comment by sudar** [comment]
@mariadanieldeepak 

Have you run `composer install`?

**Comment by mariadanieldeepak** [comment]
@sudar The above screenshot was captured after I ran `composer install`  :(

**Comment by mariadanieldeepak** [comment]
@sudar,

Thank you for answering it via Slack.
