### ISSUE TITLE
Fix Travis issue

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#161]

**Comment by sudar** [comment]
@mariadanieldeepak 

Found that we were having a syntax error in the create table SQL that was causing this.

I have fixed it in this commit - https://github.com/sudar/email-log/commit/09dc86c3f24c36e4ec5651805f3882f66e031488

**Comment by mariadanieldeepak** [comment]
@sudar,

Ah, I added the `,`.. Alright, thank you.
