### ISSUE TITLE
Test `dev/2.3.0` in WordPress 5.0

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#175]
WordPress 5.0 (which is going to be released sometime around Nov 19th) is making a fundamental change in how edit post screen will be rendered.

Download the latest beta of WordPress 5.0 from https://wordpress.org/news/2018/11/wordpress-5-0-beta-3/ and run the latest version of `dev/2.3.0` in WordPress 5.0 to see whether everything works properly.

**Comment by mariadanieldeepak** [comment]
@sudar,

I've installed WordPress 5.0 and the base plugin testing is completed so far.

I found no issues with the following:

- [x] Viewing logs
- [x] Viewing logs based on User roles

- [x] Dashboard widget display
- [x] Toggling Dashboard widget using Settings

- [x] Email Log table size notification using Cron

- [x] Removing Data on uninstall

Some of the issues I found during my testing are:

- [ ] https://github.com/sudar/email-log/issues/176 npm install Security audit

**Comment by sudar** [comment]
Awesome
