### ISSUE TITLE
Test dev/2.3.0

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#182]

**Comment by mariadanieldeepak** [comment]
✅ https://github.com/sudar/email-log/issues/113 Capture the result of the email sent and show it as s column

![image](https://user-images.githubusercontent.com/17510033/48460668-154ae100-e7f6-11e8-8400-3b9e8dc7b4ac.png)

✅ https://github.com/sudar/email-log/issues/81 Add support for multipart email and attachments

![image](https://user-images.githubusercontent.com/17510033/48461146-3a405380-e7f8-11e8-80cb-2fd4e3bafcfe.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

I've completed my testing on `dev/2.3.0` and the results look very promising. Kindly address all items marked with 🚫 in the above comment before releasing `v2.3.0`

I'm super excited for this release.

**Comment by sudar** [comment]
@mariadanieldeepak 

Awesome.

I am closing this, since all pending items are handled as seperate tickets.
