### ISSUE TITLE
Clear the notified flag whenever the settings are saved

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#184]
From #182 

> 🚫 #124 Suggestion: Notify admin when Email Logs meet a threshold

> However, I've one question. How/when would the Db Option be reset? In other words, we send the notification email and set an option Db to stop sending the same notification email. But the User has no UI to reset this option.

@mariadanieldeepak 

Let's clear it every time the settings are saved.

## Attached PR(s)
https://github.com/sudar/email-log/pull/187

**Comment by mariadanieldeepak** [comment]
@sudar,

I noted this only today. I shall update you on this soon.

**Comment by mariadanieldeepak** [comment]
@sudar,

This issue is blocked by https://github.com/sudar/email-log/issues/186

**Comment by mariadanieldeepak** [comment]
@sudar,

`composer install` pulled the required files. I'm unblocked here.

**Comment by mariadanieldeepak** [comment]
@sduar,

> I think we should add a note in the settings page after we send the notification, saying that the notification was already sent at this date and if you want it again, then click a checkbox or something to reset the flag.

I've added UI to display the last email sent date and time. The date and time format is used from the WordPress settings that is set by the user.

![image](https://user-images.githubusercontent.com/17510033/49000241-f3027d00-f17e-11e8-8a1c-4568c4067aa6.png)
