### ISSUE TITLE
Suggestion: Include Settings menu next to View Logs

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#189]
![image](https://user-images.githubusercontent.com/17510033/49154917-aade8880-f33f-11e8-8473-613e35680cb8.png)

This improves User experience.

---

## Attached PR(s)
https://github.com/sudar/email-log/pull/209

**Comment by mariadanieldeepak** [comment]
@sudar,

Kindly review this idea to proceed further.

**Comment by sudar** [comment]
Good Suggestion. We can include it as part of next milestone.
