### ISSUE TITLE
Not comaptible with PHP 7.2.1

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#198]
Here is the error

```[21-Dec-2018 13:44:01 UTC] PHP Warning: count(): Parameter must be an array or an object that implements Countable in D:\MAMP\htdocs\rcp-dev\wp-content\plugins\email-log\include\Core\EmailLogger.php on line 52```

Reported at https://wordpress.org/support/topic/php-compatibility-11/#post-11017088

**Comment by mariadanieldeepak** [comment]
@sudar,

This is handled as part of https://github.com/sudar/email-log/issues/193.
