### ISSUE TITLE
Merge 2.3.0 changes in to 2.4.0 after release

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#208]
This issue was identified as part of https://github.com/sudar/email-log/issues/189
Branch: https://github.com/sudar/email-log/tree/dev/2.4.0

After the v2.3.0 release, merge the changes back in to `dev/2.4.0` branch.

**Comment by sudar** [comment]
Closing this since we have not merged anything to 2.4.0 yet.
