### ISSUE TITLE
Use conditional Admin Notices to upsell add-ons

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#212]
Consider using the following technique to upsell add-ons.

![image](https://user-images.githubusercontent.com/17510033/54114676-f4e00b80-4410-11e9-9504-0b549d675c4f.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

I think a couple of use cases can be beneficial. All of the following cases assume that the respective notice is only shown when the add-on is not installed.

#### On the View logs page

- When there are more than 5000 logs, we can show a notice to up-sell Auto Delete logs add-on
- When could use the same threshold to up-sell More fields add-on

#### On License activation page

- If none of the add-ons has installed license then we could show a notice to up-sell bundles

**Comment by sudar** [comment]
@esudalaimadan 

Implement the following.

- [ ] If there are more than 5000 logs, then show a notice to up-sell Auto Delete logs add-on in the view logs page.
- [ ] In the settings page, add an up sell message for Auto Delete logs add-on below `Database Size Notification` setting

**Comment by sudar** [comment]
Use this library for showing dismissible notices - https://github.com/collizo4sky/persist-admin-notices-dismissal

**Comment by esudalaimadan** [comment]
Buy now link in log list page:
https://wpemaillog.com/addons/auto-delete-logs/?utm_campaign=Upsell&utm_medium=wpadmin&utm_source=log-list&utm_content=dl
---------------------
Buy now link in settings page:
https://wpemaillog.com/addons/auto-delete-logs/?utm_campaign=Upsell&utm_medium=wpadmin&utm_source=settings&utm_content=dl

**Comment by sudar** [comment]
@esudalaimadan 

Check the comment that I posted in PR https://github.com/sudar/email-log/pull/270#issuecomment-643034690
