### ISSUE TITLE
Notice in the debug log

### ISSUE THREAD

**Issue by misulicus** [sudar/email-log#217]
PHP Warning:  implode(): Invalid arguments passed in D:\MAMP\htdocs\rcp-new\wp-content\plugins\email-log\include\Core\EmailLogger.php on line 63

Just a regular sign up mail with no attachments at all.

**Comment by sudar** [comment]
@misulicus 

Thanks for reporting the issue.

Looks like this happens because of the new code that was added to handle attachments.

Is this the default email generated by WordPress?

**Comment by sudar** [comment]
@misulicus 

I explored this further and it seems that the above warning might be thrown if the `wp_mail` filter is called with an array that has a string value for attachments key.

The current code handled the case where the `attachment` is missing or is an array.

I will add some checks to handle cases when the attachment key a string, but I am curious how in your case the `wp_mail` filter was called with an array that has string value for `attachments` key. Are you using any plugin that generates the email or sends the email using a service like SendGrid etc?

**Comment by gbhall99** [comment]
Hey, I'm also seeing this error all over my error_log.

I do use WooCommerce Follow up Mails.
Any idea when there is a fix planned?

Regards and thanks

**Comment by misulicus** [comment]
@sudar i'm using the plugin on all of my development sites, mostly working with Eeasy Digital Downloads and Restrict Content Pro

**Comment by misulicus** [comment]
@sudar just as a heads up i'm on 2.3.1 version and still receiving the notice

`PHP Warning:  implode(): Invalid arguments passed in D:\MAMP\htdocs\rcp-dev\wp-content\plugins\email-log\include\Core\EmailLogger.php on line 63`

**Comment by sudar** [comment]
@mihaijoldis @gbhall99 

I just released v2.3.2 of the plugin which should fix the above warning. It should have been sooner but the release got delayed because of some unplanned reasons.

Please try it out and let me know if you are still getting the warning.
