### ISSUE TITLE
Suggestion: Show list of active Email log add-ons

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#221]
![image](https://user-images.githubusercontent.com/17510033/60152893-20d89e80-9800-11e9-816e-327ef5977b51.png)

Value: This will enable us to highlight what the add-on does in a one-liner. For example, 

Mask Fields add-on: Active (We can even have an Active/Disabled UI switch)
_Masks the fields in the logged emails for privacy_

### Tasks

- [ ] Show Add-on name & version along w/ Email Log core version.
- [ ] Installed & Active
- [ ] Installed & In-active

---
#### Attached PR(s)
- https://github.com/sudar/email-log/pull/242

**Comment by mariadanieldeepak** [comment]
@sudar,

Here is how the Dashboard widget will look after merging this PR.

![image](https://user-images.githubusercontent.com/17510033/62421259-9f0c4880-b6bc-11e9-8943-d6f4c3a13acf.png)

**Comment by sudar** [comment]
I am going to close this as `wontfix`.

Even though the idea is good, it looks very redundant since we already have an Add-ons page.
