### ISSUE TITLE
Capture the error message if the email fails

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#224]
If the email fails, then capture the error response.

- [x] Create a new column in the table. Also increment the db option and code to modify the table
- [x] Store the error message in the new column
- [ ] If the email is just paused (see #220 ) then add a message that says Email is paused
- [x] Show the error message (or the pause message) when the user hovers over the x icons. See #215 

---
#### Attached PR(s)
- https://github.com/sudar/email-log/pull/240

#### Merged PR(s)
- https://github.com/sudar/email-log/pull/218

**Comment by mariadanieldeepak** [comment]
Update:

The error message column is now storing the message.

![image](https://user-images.githubusercontent.com/17510033/62263497-17afa280-b43a-11e9-91d5-b744dfc84946.png)

**Comment by mariadanieldeepak** [comment]
Update (Aug 2)

Error message on hover is implemented.

![image](https://user-images.githubusercontent.com/17510033/62340740-34ada980-b4fe-11e9-9032-4c248083656a.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

> - [ ] If the email is just paused (see #220 ) then add a message that says Email is paused

This should be handled as part of https://github.com/sudar/email-log/issues/220

Other than that, this issue is completed. I'm self-reviewing it and assigning it to you for further review.
