### ISSUE TITLE
Use  jdgrimes/wpppb instead of jdgrimes/wp-plugin-uninstall-tester

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#230]
![image](https://user-images.githubusercontent.com/17510033/61099226-39db8380-a47f-11e9-9398-82a1f85c5e89.png)

https://github.com/sudar/email-log/blob/1cc571ba0e7400e009f741e1eeabe4c65d216fd0/composer.json#L31

**Comment by sudar** [comment]
@mariadanieldeepak 

I know that the package is abandoned.

But `jdgrimes/wpppb` doesn't have the feature that is present in `jdgrimes/wp-plugin-uninstall-tester` which we are using.

We need to find an alternative and till then we can continue to use `jdgrimes/wp-plugin-uninstall-tester`
