### ISSUE TITLE
Replace bower with npm and use npm postinstall to automatically copy vendor files

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#231]
- [x] Replace bower with npm
- [x] Create a new vendor task in grunt to copy vendor files into assets directory
- [x] Use npm `postinstall` to automatically call `grunt vendor`
- [x] Audit npm packages

**Comment by sudar** [comment]
@mariadanieldeepak 

Can you explain a bit more?

Do you want to include scripts in package json for running grunt?
