### ISSUE TITLE
Defaulf email content type in View Content popup

### ISSUE THREAD

**Issue by rajanvijayan** [sudar/email-log#232]
Even user sends a raw content email, But the details automatically show HTML content. 

Does it make sense? If a user sends Raw content the details popup shows Raw content automatically at the same time users send HTML content its shows HTML content. 

![Screenshot from 2019-07-22 18-41-38](https://user-images.githubusercontent.com/2988033/61635419-2e732e00-acb1-11e9-9976-262ff7cc1b57.png)

---
Attached PR(s)
- https://github.com/sudar/email-log/pull/243

**Comment by sudar** [comment]
@rajanit2000 

Thanks for the suggestion. We will add it to the todo list.

**Requirement**:

- Highlight Raw content tab if the email was sent as text email (content type)
- Highlight HTML content tab, if the email was either sent as HTML email or if the content type is missing.
