### ISSUE TITLE
Suggession: <pre> tag instead of <textarea>

### ISSUE THREAD

**Issue by rajanvijayan** [sudar/email-log#233]
In Raw email content tab have textarea, But it's no use in this case. because we does not have any form in this tab.

![Screenshot from 2019-07-22 18-41-11](https://user-images.githubusercontent.com/2988033/61635875-1c45bf80-acb2-11e9-88d6-1a24674cc441.png)

Can we change with `<pre>` tag instead of `<textarea>`

![Screenshot from 2019-07-22 18-40-36](https://user-images.githubusercontent.com/2988033/61635889-24056400-acb2-11e9-9e6b-5c05a6b9c57f.png)

---
Attached PR(s)
- https://github.com/sudar/email-log/pull/243

**Comment by sudar** [comment]
@rajanit2000 

Good suggestion. We will add it to the todo list.
