### ISSUE TITLE
Support array values in `to` field

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#234]
Blocks https://github.com/sudar/email-log-mask-fields/issues/5

Once this is done, proceed with https://github.com/sudar/email-log-mask-fields/issues/5

**Comment by sudar** [comment]
@mariadanieldeepak 

I checked and as far as I know, the `dev/2.3.2` branch already supports array values in `to` field.

Can you check?

**Comment by mariadanieldeepak** [comment]
@sudar ,

Could you execute the following piece of code to send an email, to see the values that you receive at https://github.com/sudar/email-log/blob/dev/2.3.2/include/Core/DB/TableManager.php#L102

```
wp_mail( array( 'daniel@danieldeepak.com', 'sudar@sudarmuthu.com' ), 'Email w/ array in `to` param', 'This is a test email', '', array() );
```

I'm trying to log the following values

![image](https://user-images.githubusercontent.com/17510033/62715349-f3495c80-ba1d-11e9-8aa4-50094c644ade.png)

and this is what I get

![image](https://user-images.githubusercontent.com/17510033/62715421-17a53900-ba1e-11e9-99d5-e11f50a8a0b2.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

This was happening because of a bug in Mask Fields add-on. It is now fixed in Mask Fields add-on (https://github.com/sudar/email-log-mask-fields/commit/93790bb6338ee8866fe605a24318e6baa3de20fb) and I have verified that this works.

Hence closing this.
