### ISSUE TITLE
Check Admin UI in WordPress 5.3

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#245]

**Comment by esudalaimadan** [comment]
@sudar There are no major differences in UI.  I found two minor issues.
![Screenshot from 2019-11-14 10-52-50](https://user-images.githubusercontent.com/38071735/68829534-0cbe0c80-06cf-11ea-9049-6a6ce48c1912.png)

![Screenshot from 2019-11-14 10-57-04](https://user-images.githubusercontent.com/38071735/68829551-1a739200-06cf-11ea-8f67-ff2966779fef.png)

**Comment by esudalaimadan** [comment]
![Screenshot from 2019-12-02 12-29-35](https://user-images.githubusercontent.com/38071735/69937603-349bd580-1501-11ea-93af-0946f7cc3ff2.png)
