### ISSUE TITLE
Compatibility with Gmail STMP plugin

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#247]
A user reported that emails sent via [Gmail STMP](https://wordpress.org/plugins/gmail-smtp/) plugin are not getting logged.

@esudalaimadan See if you are able to replicate the issue.

**Comment by esudalaimadan** [comment]
Assigning this back to Sudar as I am facing issues in setting up `GMail SMTP` plugin in my local.

**Comment by sudar** [comment]
Closing this since I am not able to replicate the issue.
