### ISSUE TITLE
Buddypress emails do not appear in the log

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#249]
Originally reported at https://wordpress.org/support/topic/buddypress-emails-do-not-appear-in-the-log/#post-12203122

**Comment by esudalaimadan** [comment]
BuddyPress does not use `wp_mail` for sending emails and so email log is not showing up buddy press emails.
1) We need to add this in the compatiblity section of the docs.
`add_filter( 'bp_email_use_wp_mail', '__return_true' )`
2) We also need to raise a request with BuddyPress about it.

**Comment by sudar** [comment]
Relevant line in Buddypress source code is https://github.com/buddypress/BuddyPress/blob/master/src/bp-core/bp-core-functions.php#L3177

We also need explore ways to use the hooks generated by BuddyPress to log the email.
