### ISSUE TITLE
Test compatibility with PHP 7.4

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#253]
Reported at https://wordpress.org/support/topic/still-logged-as-sent-when-wp_mail-returns-error/

**Comment by knutsp** [comment]
PHP is not the real issue. The fact that some PHP 7.4 distributions, as of today, has a bug that affects wp_mail() is a coincidence that just revealed that emails get logged even if there is a detectable error.

If the Health Check and Troubleshooting plugin as able to detect this, then this plugin also should be, IMHO.

**Comment by sudar** [comment]
Looks like WordPress itself is not aware that the email was not sent properly. So there is no way for us to detect it. Hence closing it.

But in future if there is a way for us to detect that email has failed, then we will revisit it again.
