### ISSUE TITLE
Compatibility with WordPress 5.4

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#259]

**Comment by esudalaimadan** [comment]
**WordPress 5.4 - Email Log master - chrome browser(Version 70.0.3538.67):**

![wp-5 4-email-log-master-chrome](https://user-images.githubusercontent.com/38071735/78329544-99466a00-759f-11ea-8bcc-f3057a5f71f7.png)

**WordPress 5.4 - Email Log master - Firefox browser(Version 71.0):**

![wp5 4-email-log-master-firefox](https://user-images.githubusercontent.com/38071735/78330331-643b1700-75a1-11ea-9719-970e8ad48341.png)

**Comment by esudalaimadan** [comment]
**WordPress 5.4 - Email Log dev/2.4.0 - chrome browser(Version 70.0.3538.67):**
![wp5 4-email-log-dev2 4 0-chrome](https://user-images.githubusercontent.com/38071735/78333216-0ad5e680-75a7-11ea-861c-94d10c91e3d2.png)

**WordPress 5.4 - Email Log dev/2.4.0 - firefox browser(Version 71.0):**
![wp5 4-email-log-dev2 4 0-firefox](https://user-images.githubusercontent.com/38071735/78333268-23460100-75a7-11ea-9fe8-9e8021e45baa.png)

**Comment by esudalaimadan** [comment]
Other stuff looks good.

**Comment by sudar** [comment]
Okay, fix the design issues.

**Comment by esudalaimadan** [comment]
We are planning to use css grid option.
