### ISSUE TITLE
Compatibility with Contact Form 7

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#260]
A user reported that they are getting fatal errors when using contact form 7.

Details at https://wordpress.org/support/topic/call-to-undefined-function-emaillogutil/#post-12711922

Try to replicate it and see whether there are any issues with that plugin.

**Comment by esudalaimadan** [comment]
I am able to see the emails in email log. I am not able to replicate the issue.
Email log - master branch.
WP - 5.4.1
PHP - 7.2.24

**Comment by sudar** [comment]
Closing this, since we are not able to replicate it.
