### ISSUE TITLE
Test latest released version in WordPress 5.4

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#283]
Test the latest released version (v2.4.0) from master branch in WordPress 5.4 and let me know if you are still seeing design issues in add-on list page

**Comment by esudalaimadan** [comment]
![Screenshot from 2020-07-06 12-19-56](https://user-images.githubusercontent.com/38071735/86564919-98e5b280-bf84-11ea-8d7b-3f5e45d41ade.png)
Looks good both in Firefox and Chrome.
