### ISSUE TITLE
Screen options: Unable to change entries per page

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/email-log#286]
Screen options: Unable to change entries per page.

**Comment by esudalaimadan** [comment]
@sudar For some reason, the usermeta does not have email log list page entries.  Also the `set-screen-option` hook's callback first argument is integer instead of boolean.
Note: per page entries work fine for posts listing admin page.

Also, set-screen-option works with `init` and will not work with `admin_menu`.

**Comment by esudalaimadan** [comment]
@sudar With WordPress 5.5, entries per page works.

**Comment by sudar** [comment]
Closing this, since it is working.
