### ISSUE TITLE
Use the timeformat that is selected in WordPress settings page

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#288]
Requested at https://wordpress.org/support/topic/please-bring-back-custom-time-format/

**Comment by knutsp** [comment]
The WordPress option time_format usually does not contain seconds. It's intended for showing post / updated times on front. If this plugin, that deals with more accurate and internal logging,  wants to have seconds it can better be achieved with a translatable string, with 'g:i:s' as the base. This is how other plugins usually do it for time displays in wp-admin.

**Comment by sudar** [comment]
@knutsp 

Thanks for providing additional insight into the time format. We will implement it based on your suggestion.

**Comment by sudar** [comment]
Thanks @knutsp 

We have implemented it based on your suggestion and it will be released as part of v2.4.3
