### ISSUE TITLE
No Email Log for Emails sent by MailPoet Plugin

### ISSUE THREAD

**Issue by oldmankit** [sudar/email-log#29]
[MailPoet](https://wordpress.org/plugins/wysija-newsletters/) is a plugin that allows you to do newsletters etc. all from Wordpress. It's got over 200,000+ active installs according to the WordPress plugin page.

Currently no emails that are sent by MailPoet appear in my Email log. Is this a known issue?

**Comment by sudar** [comment]
No. This is not a known issue.

The email should get logged if that plugin is using `wp_mail` function.

Let me investigate it a bit and get back to you.

**Comment by sudar** [comment]
Hello @oldmankit 

I finally got some time to investigate this further and it seems that MailPoet plugin is not using WordPress `wp_mail` function and instead it is calling PHP's `mail` function directly. I am not sure what is the reason they are doing it.

I have posted about it in [MailPoet support forum](https://wordpress.org/support/topic/send-mail-using-built-in-wp_mail-function?replies=1#post-7818136) and waiting for the authors of the plugin to reply back.

**Comment by sudar** [comment]
Bad news!

MailPoet is not using `wp_mail` function and they are not even interested in adding the filters. Details here https://wordpress.org/support/topic/send-mail-using-built-in-wp_mail-function?replies=5#post-7824781

At this point, nothing can be done from Email Log plugin to enable logging.

I will add a note about it in FAQ's.

**Comment by oldmankit** [comment]
Hi there Sudar,

Thanks very much for getting back to me, and for following-up this issue. It looks like you've done all you can do.

Thank you again,
Kit

**Comment by sudar** [comment]
Yeah, unfortunately I can't do anything at this point in time except wait for Mail Poet to add those filters :(

I will keep an eye on that thread and Mail Poet release notes and will test it as soon as they add the filters. Also thanks for adding a note about the Email Log plugin the MailPote support thread.
