### ISSUE TITLE
Check compatibility with bbPress

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#298]
Reported at https://wordpress.org/support/topic/bp_send_email-is-not-logged/

**Comment by esudalaimadan** [comment]
Emails triggered by bbPress are getting logged in email logs.  I doubt customer is talking about buddypress.  Will check and let you know the status.

**Comment by esudalaimadan** [comment]
buddypress emails are also getting logged.

**Comment by sudar** [comment]
Thanks for exploring @esudalaimadan 

Closing this as invalid.
