### ISSUE TITLE
Increase the size of the TO field in the email log table to 250 characters

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#31]
---

## Attached PR(s)
https://github.com/sudar/email-log/pull/155

**Comment by sudar** [comment]
@mariadanieldeepak 

Explore the option to do this and also check what is the current size.

**Comment by mariadanieldeepak** [comment]
@sudar,

The current size of the column is `100`.

https://github.com/sudar/email-log/blob/dev/2.3.0/include/Core/DB/TableManager.php#L251 

We must do the following to ensure that the column length is `250` chars.

- Setting the above line to 250 will affect only the newer installs.
- To modify the existing installs, we can leverage the DB version that we store as an option in the Options table. All existing users will have the current DB version set to `0.1` (https://github.com/sudar/email-log/blob/dev/2.3.0/include/Core/DB/TableManager.php#L263)
- We should be running an alter command and also update the DB version.

```
$sql = 'ALTER TABLE ' . $table_name . ' MODIFY to_email VARCHAR(250);';
```

**Comment by mariadanieldeepak** [comment]
@sudar,

May I know why we should be increasing the size of the column? I mean it is obvious that we're doing this to store more data, but most emails should be less than 100 right? Is it because that we support multiple emails?

**Comment by mariadanieldeepak** [comment]
@sudar,

This is now ready for your review at https://github.com/sudar/email-log/pull/155

**Comment by mariadanieldeepak** [comment]
@sudar,

I've fixed the review comments and this is now ready.
