### ISSUE TITLE
Not Logging Content of Emails for Sites on https

### ISSUE THREAD

**Issue by KTS915** [sudar/email-log#34]
Email Log is working fine on my localhost test site, but on my live site, clicking on the View Content link simply generates a blank lightbox.

I've tried switching to a default theme and turning off other plugins, and it made no difference, so my conclusion is that the issue lies with the fact that the live site is using https.

**Comment by sudar** [comment]
Thanks for reporting this issue.

Can you find out if there are any JavaScript or PHP errors generated when you try to view the log?

**Comment by KTS915** [comment]
No, there are no PHP or javascript errors.

I've just tested a couple of other plugins to see how they behave. Interestingly, Postman SMTP has the same problem, but [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) _is_ able to show the email content. I don't know if that provides a clue.

**Comment by sudar** [comment]
That's really strange. Would it be possible for you to provide me access to your server so that I can do some debugging?

**Comment by KTS915** [comment]
Yes. I've just completed the contact form on your web page.

**Comment by KTS915** [comment]
Just so that anyone reading this knows, the issue turned out to be that the .htaccess file on my site's root domain included a line that set the X-Frame-Options header to DENY. When changed to SAMEORIGIN, everything worked fine. So there was no problem with the plugin at all.
