### ISSUE TITLE
Replace wp_get_sites() with get_sites() in email-log/include/Core/DB/TableManager.php

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#66]
- [ ] Replace `wp_get_sites()` with `get_sites()` in `email-log/include/Core/DB/TableManager.php`
- [ ] Test the above change and make sure it works
- [ ] Replace `wp_get_sites()` with `get_sites()` in `email-log/uninstall.php` in line number 16
- [ ] Test the above change and make sure it works

**Comment by sudar** [comment]
When we make this change, we need to make sure that we don't break it in WordPress < 4.6

**Comment by sudar** [comment]
@wp-networks 

Thanks for letting us know about the replacement that is needed in the `uninstall.php` file as well.

I have added it to the list.
