### ISSUE TITLE
Update jdgrimes/wp-plugin-uninstall-tester package

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#72]
Warning while composer update:

Package jdgrimes/wp-plugin-uninstall-tester is abandoned, you should avoid using it. Use jdgrimes/wpppb instead.

**Comment by sudar** [comment]
I explored this further and found that for what we are doing right now the `jdgrimes/wp-plugin-uninstall-tester` is fine. `jdgrimes/wpppb` might be a overkill and it also expects the source code to follow a different folder structure.

We can update to `jdgrimes/wpppb` or something else if anything breaks or if we find an better alternative.
