### ISSUE TITLE
QA - Fix Button label

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#78]
The **Export Logs** addon button label says `Activate License to Use` while all other labels say `Activate License to Install`. This has to changed for consistency.

![image](https://cloud.githubusercontent.com/assets/17510033/25466005/8a7ac698-2b23-11e7-9c64-5456f2bb3b41.png)

**Comment by sudar** [comment]
@mariadanieldeepak It is not a bug, it's a feature ;)

You get the message `Activate License to Use`, if you already have the add-on installed and `Activate License to Install` if you don't have the add-on installed.

In your case it looks like you have that add-on installed.

**Comment by mariadanieldeepak** [comment]
Oops, (face palm).. Got it, thank you. I did install Export Logs.
