### ISSUE TITLE
Suggestion: Allow users to re-order columns in View Logs

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#82]

**Comment by sudar** [comment]
@mariadanieldeepak 

Have you seen this happen in any of WordPress built-in UI?

**Comment by mariadanieldeepak** [comment]
@sudar,

Nope. But wanted to have a configuration on Settings page to specify the Order of Columns.

**Comment by sudar** [comment]
@mariadanieldeepak 

I am closing this since I feel that this may be a over kill.

Also the current WordPress admin UI don't provide this. So it will be confusing to users.

We can revisit again if the need rises.
