### ISSUE TITLE
Update Anchor links on Plugin screens help (July 21, 2017)

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#85]

**Comment by mariadanieldeepak** [comment]
**Plugin screen help links**

![image](https://user-images.githubusercontent.com/17510033/28101882-0fbd8a42-66e9-11e7-8dc8-858eb62491bf.png)

The following are the existing links.

- [Plugin Homepage/support](http://sudarmuthu.com/wordpress/email-log)
- [Plugin author's blog](http://sudarmuthu.com/blog)
- [Other Plugin's by author](http://sudarmuthu.com/wordpress/)

I'm planning to change the above links to the following.

- [Plugin Homepage](http://wpemaillog.com/)
- [Plugin Support](https://wpemaillog.com/support/)
- [Plugin Addons](https://wpemaillog.com/store/)

Let me know if you need me to change anything.

**Comment by mariadanieldeepak** [comment]
The plugin screen help links have been updated.

![image](https://user-images.githubusercontent.com/17510033/28149221-a7ab9f68-67a9-11e7-9a67-f3634a675a1c.png)

PR has been sent.

**Comment by sudar** [comment]
@mariadanieldeepak 

I have merged the pull request.

Can you also add a note below the plugin description and link to the documentation pages?
