### ISSUE TITLE
Don't `wpautop` for html emails

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#86]
Just confirm whether we are applying `wpautop` to html emails.

More details at https://wordpress.org/support/topic/no-wpautop-for-html-emails/

**Comment by podkot** [comment]
looks like it was removed in c73b895b9d6a00e75c617b2dca1fc7a91c8934f7

but for plain text emails `wpautop` should be ok

**Comment by mariadanieldeepak** [comment]
We're bidding goodbye to `wpautop` in v2.0 to both HTML and Text versions.

**HTML**
https://github.com/sudar/email-log/blob/master/include/Core/Request/LogListAction.php#L86

**Text**
https://github.com/sudar/email-log/blob/master/include/Core/Request/LogListAction.php#L89

**Comment by sudar** [comment]
Perfect. Thanks @mariadanieldeepak 

@podkot This will get released as part of our v2.0 release in a couple of days.
