### ISSUE TITLE
Date issue with duplicator plugin

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#88]
Reported at https://wordpress.org/support/topic/not-compatible-with-duplicator/

> The problem is whenever I try to install from duplicator backup, the date of all the email logs changes to the date and time at which the backup was installed which makes the backup almost useless.

**Comment by mariadanieldeepak** [comment]
I tried to analyze what could go wrong, but couldn't figure out. The following would helps to get a direction in solving this.

- Getting the copy the SQL file that Duplicator Plugin generated (at least the `email_log` table values)

**Comment by mariadanieldeepak** [comment]
@sudar,

The user [reported](https://wordpress.org/support/topic/not-compatible-with-duplicator/#post-9411106) that the issue has been fixed by their host. He hasn't mentioned what steps they have taken but the issue is resolved.

**Comment by sudar** [comment]
The user who reported that the issue was fixed is a completely new user who tried to hijack the thread.

This is the last reply that we got from that thread - https://wordpress.org/support/topic/not-compatible-with-duplicator/#post-9410293

**Comment by mariadanieldeepak** [comment]
Oops.

**Comment by sudar** [comment]
@mariadanieldeepak 

Check https://wordpress.org/support/topic/not-compatible-with-duplicator/#post-9410293 and let me know if we would any further information from the user to debug this.

**Comment by sudar** [comment]
Closing this, since we are not able to replicate the issue.
