### ISSUE TITLE
Suggestion: Allow Users to export/import Email Log CSV

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#90]

**Comment by mariadanieldeepak** [comment]
> Are you talking about importing the exported email log csv file?

Yeap, exactly.

**Comment by mariadanieldeepak** [comment]
@Sudar,

Could you please create a repo for this add-on?

**Comment by sudar** [comment]
I have created a new repo and invited you to it.

Let's follow the development there.
