### ISSUE TITLE
GUI option to change the capability of the user who can view logs

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#93]
Right now we don't have a settings page.

We can use the settings page that we will be creating for #89

**Comment by mariadanieldeepak** [comment]
@sudar,

- The GUI option has been implemented and the PR has been sent - https://github.com/sudar/email-log/pull/100
 - Also, I'm waiting for the reference plugin that you had mentioned.

**Comment by sudar** [comment]
@mariadanieldeepak 

I am not able to get hold of the plugin that I spoke about earlier.

I have the following idea for this feature.

In the UI we will list all the user roles (including the custom ones) as checkboxes with a message that only the users who belong to the selected user role could access the page. By default we will select the Admin user role only. This would be stored as an option. We should also link to the documentation explain this.

In the code we will check if the option is set. If yes, then it will take precedence. If it is not set then the filter will take precedence.

We will do the same thing for view the content of the email as well.

**Comment by mariadanieldeepak** [comment]
@sudar,

> In the UI we will list all the user roles (including the custom ones) as checkboxes with a message that only the users who belong to the selected user role could access the page. By default we will select the Admin user role only. This would be stored as an option. We should also link to the documentation explain this.

I shall use the following method to check the role and proceed accordingly.
https://wordpress.stackexchange.com/a/5048/83739

> In the code we will check if the option is set. If yes, then it will take precedence. If it is not set then the filter will take precedence.

Alright, got it.

**Comment by sudar** [comment]
> I shall use the following method to check the role and proceed accordingly.
https://wordpress.stackexchange.com/a/5048/83739

👍

**Comment by sudar** [comment]
Once this is done, handle https://github.com/sudar/wp-email-log-site/issues/69

**Comment by mariadanieldeepak** [comment]
This has been implemented and the PR #100 has been sent.

**Comment by sudar** [comment]
So far good. We need to do these additional things as well.

- Show the settings block in the settings page only to admins
- We need to prevent a user from viewing a page by directly going to the url if he doesn't have access to it.
- We need two blocks. One for seeing the list of logs and another for viewing the content of the email.
