### ISSUE TITLE
Suggestion: Allow users to View Logs by User Role

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/email-log#94]
This could be built as an add-on. It will help the Site admins to allow users of certain roles to view/manage Email Log.

**Caveats**

If this add-on is built, having the GUI option to manage capability would seem redundant(#93). Kindly correct me, if I'm wrong.

**Comment by sudar** [comment]
It is a very basic feature. I feel it should be part of the free plugin itself.

Let's do #93 instead of creating a new add-on.

**Comment by mariadanieldeepak** [comment]
Alright, #93 is in-progress, hence closing the to-do.
